apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: test-instructlab01
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  test-instructlab01
    app.kubernetes.io/part-of: test-instructlab01  
  name: test-instructlab01
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  test-instructlab01 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  test-instructlab01
    spec:
      containers:
      - env:
        - name: MODEL_ENDPOINT
          value: http://test-instructlab01-model-server:8001
        image:  quay.io/yangcao/chatbot:latest
        name: app-inference
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true